[package]
name = "guild_core"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["full"] }
